spring.application.name=proyecto-final-poo

# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_ventas
spring.datasource.username=root
spring.datasource.password=1234

# Configuración JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Mostrar consultas SQL con valores más legibles
logging.level.org.hibernate.SQL=DEBUG

# Puerto de Spring Boot
server.port=8080

# Usuario de Spring Security
spring.security.user.name=admin
spring.security.user.password=123