spring.datasource.url=jdbc:jdbc:mysql://localhost:3306/gestion_ventas
spring.datasource.username=root
sring.datasource.password=
spring.sql.init.mode=always
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.sql.init.data-locations=classpath:sql/data.sql
spring.security.user.name=admin
spring.security.user.password=XmjZ8